import { useState } from 'react';
// @ts-ignore
import { ArrowLeft, Home, MessageSquareQuote, FileCheck } from 'lucide-react';

const LANGUAGES = [
  { id: 'de', name: 'Deutsch', germanCountry: 'Deutschland', countryCode: 'de' },
  { id: 'en', name: 'English', germanCountry: 'Großbritannien / Englisch', countryCode: 'gb' },
  { id: 'fr', name: 'Français', germanCountry: 'Frankreich', countryCode: 'fr' },
  { id: 'es', name: 'Español', germanCountry: 'Spanien', countryCode: 'es' },
  { id: 'it', name: 'Italiano', germanCountry: 'Italien', countryCode: 'it' },
  { id: 'ru', name: 'Русский', germanCountry: 'Russland', countryCode: 'ru' },
  { id: 'pl', name: 'Polski', germanCountry: 'Polen', countryCode: 'pl' },
  { id: 'ro', name: 'Română', germanCountry: 'Rumänien', countryCode: 'ro' },
  { id: 'tr', name: 'Türkçe', germanCountry: 'Türkei', countryCode: 'tr' },
  { id: 'sl', name: 'Slovenščina', germanCountry: 'Slowenien', countryCode: 'si' },
  { id: 'hu', name: 'Magyar', germanCountry: 'Ungarn', countryCode: 'hu' },
  { id: 'uk', name: 'Українська', germanCountry: 'Ukraine', countryCode: 'ua' },
  { id: 'hi', name: 'हिन्दी', germanCountry: 'Indien', countryCode: 'in' },
  { id: 'bg', name: 'Български', germanCountry: 'Bulgarien', countryCode: 'bg' },
  { id: 'cs', name: 'Čeština', germanCountry: 'Tschechien', countryCode: 'cz' },
  { id: 'lt', name: 'Lietuvių', germanCountry: 'Litauen', countryCode: 'lt' },
  { id: 'nl', name: 'Nederlands', germanCountry: 'Niederlande', countryCode: 'nl' },
  { id: 'hr', name: 'Hrvatski', germanCountry: 'Kroatien', countryCode: 'hr' },
];

const TEXT_DATABASE = {
  de: "Erklärungen zum Dokument Zustellungsvollmacht.\n\nIm oberen Drittel des Dokuments befinden sich zunächst die Kontaktdaten der ausstellenden Polizeidienststelle sowie Felder für Ort, Datum und die Vorgangsnummer.\n\nDirekt darunter folgen die vollständigen Personalien, einschließlich Name, Geburtsdaten, Staatsangehörigkeit, Adresse und Beruf.\n\nIm Anschluss wird ausgeführt, welcher rechtliche Verstoß konkret vorgeworfen wird, wobei in separaten Zeilen unterschieden wird, ob es sich um eine Ordnungswidrigkeit oder eine Straftat handelt. Der Verstoß wird handschriftlich eingetragen.\n\nDaraufhin ermächtigt die betroffene Person durch Ankreuzen eine deutsche Behörde, wie etwa das Amtsgericht Lörrach oder das Regierungspräsidium Karlsruhe, offizielle Briefe und Strafbefehle stellvertretend für sie in Empfang zu nehmen. Die Schriftstücke werden dann an den Vollmachtgeber übersandt.\n\nEin kurzer Textblock darunter belehrt zudem über die Rechte bei einer eventuellen Beschlagnahme von Gegenständen und weist darauf hin, dass man dagegen ohne bestimmte Form oder Frist eine gerichtliche Entscheidung beantragen kann.\n\nAuf der Rückseite des Dokuments wird die Person über ihre zwingenden Mitwirkungspflichten aufgeklärt, wie etwa die sofortige Mitteilung an die Behörde bei einem Wohnortwechsel. Wer keinen festen Wohnsitz hat, muss sich zudem regelmäßig und eigeninitiativ bei der bevollmächtigten Behörde – deren genaue Kontaktdaten dort nochmals aufgeführt sind – melden, um nach eingegangener Post zu fragen und diese selbstständig abzuholen. Ein besonders wichtiger rechtlicher Hinweis im unteren Bereich besagt, dass alle Fristen, wie beispielsweise für einen Einspruch gegen eine Strafe, exakt an dem Tag beginnen, an dem der Brief bei der bevollmächtigten Behörde in Deutschland eingeht. Die Frist beginnt ausdrücklich nicht erst dann, wenn die betroffene Person den Brief tatsächlich in den Händen hält oder abholt. Über diesen Weg können zudem auch Ladungen zu einer Gerichtsverhandlung rechtssicher zugestellt werden.\n\nFast am Ende des Dokuments befinden sich zwei Fragen mit Ja/Nein-Kästchen: Hier kann die Person zustimmen, eine Geldauflage zur Einstellung des Verfahrens zu zahlen, und ankreuzen, ob sie in diesem Fall auf eine formelle postalische Bestätigung über die Einstellung verzichtet. Den Abschluss bildet der Unterschriftenbereich, in dem angekreuzt wird, in welche Sprache das Formular übersetzt wurde, ob ein Dolmetscher anwesend war und dass die Vollmacht freiwillig erteilt sowie eine Kopie ausgehändigt wurde. Ganz unten links leistet schließlich die betroffene Person ihre Unterschrift, während unten rechts der zuständige Polizeibeamte unterschreibt.",
  en: "Explanations for the Delivery Authorization Document (Zustellungsvollmacht).\n\nIn the upper third of the document, you will first find the contact details of the issuing police department as well as fields for the location, date, and case number.\n\nDirectly below this are the complete personal details, including name, date of birth, nationality, address, and occupation.\n\nFollowing this, the specific legal violation you are accused of is detailed, with separate lines distinguishing between an administrative offense (Ordnungswidrigkeit) and a criminal offense (Straftat). The violation is entered by hand.\n\nThe affected person then authorizes a German authority, such as the District Court of Lörrach or the Regional Council of Karlsruhe, by checking a box, to receive official letters and penalty orders on their behalf. The documents are then forwarded to the person granting the authorization.\n\nA short text block below advises on the rights in the event of a possible confiscation of items and points out that one can request a judicial decision against this without any specific form or deadline.\n\nOn the back of the document, the person is informed of their mandatory obligations to cooperate, such as immediately notifying the authority of a change of residence. Anyone without a fixed address must also proactively and regularly contact the authorized authority - whose exact contact details are listed there again - to ask about received mail and collect it themselves. A particularly important legal notice at the bottom states that all deadlines, for example for an appeal against a penalty, start exactly on the day the letter is received by the authorized authority in Germany. The deadline expressly does not begin only when the affected person actually holds or collects the letter. Summonses to a court hearing can also be legally served via this route.\n\nAlmost at the end of the document are two questions with Yes/No boxes: Here the person can agree to pay a monetary condition to discontinue the proceedings, and check whether they waive a formal postal confirmation of the discontinuation in this case. The conclusion is the signature area, where it is checked into which language the form was translated, whether an interpreter was present, and that the authorization was given voluntarily and a copy was handed out. Finally, at the bottom left, the affected person provides their signature, while the responsible police officer signs at the bottom right.",
  fr: "Explications concernant le document Procuration de signification (Zustellungsvollmacht).\n\nDans le tiers supérieur du document se trouvent d'abord les coordonnées du service de police émetteur ainsi que des champs pour le lieu, la date et le numéro de dossier.\n\nJuste en dessous figurent les données personnelles complètes, y compris le nom, la date de naissance, la nationalité, l'adresse et la profession.\n\nEnsuite, l'infraction légale spécifique qui vous est reprochée est détaillée, avec des lignes distinctes indiquant s'il s'agit d'une infraction administrative (Ordnungswidrigkeit) ou d'une infraction pénale (Straftat). L'infraction est inscrite à la main.\n\nLa personne concernée autorise ensuite une autorité allemande, comme le tribunal de district de Lörrach ou le conseil régional de Karlsruhe, en cochant une case, à recevoir des lettres officielles et des ordonnances pénales en son nom. Les documents sont ensuite transmis à la personne qui accorde l'autorisation.\n\nUn court bloc de texte en dessous informe sur les droits en cas d'éventuelle confiscation d'objets et souligne que l'on peut demander une décision judiciaire à ce sujet sans forme ni délai précis.\n\nAu dos du document, la personne est informée de ses obligations de coopération impératives, telles que la notification immédiate à l'autorité d'un changement de domicile. Toute personne sans domicile fixe doit également contacter de manière proactive et régulière l'autorité autorisée - dont les coordonnées exactes y figurent à nouveau - pour s'informer du courrier reçu et le récupérer elle-même. Un avis juridique particulièrement important en bas précise que tous les délais, par exemple pour un recours contre une sanction, commencent exactement le jour où la lettre est reçue par l'autorité autorisée en Allemagne. Le délai ne commence expressément pas seulement lorsque la personne concernée tient ou récupère réellement la lettre. Les convocations à une audience du tribunal peuvent également être signifiées légalement par cette voie.\n\nPresque à la fin du document se trouvent deux questions avec des cases Oui/Non : ici, la personne peut accepter de payer une condition pécuniaire pour classer la procédure, et cocher si elle renonce à une confirmation postale formelle du classement dans ce cas. La conclusion est la zone de signature, où il est coché dans quelle langue le formulaire a été traduit, si un interprète était présent, et que l'autorisation a été donnée volontairement et qu'une copie a été remise. Enfin, en bas à gauche, la personne concernée appose sa signature, tandis que l'officier de police responsable signe en bas à droite.",
  es: "Explicaciones sobre el documento Autorización de entrega (Zustellungsvollmacht).\n\nEn el tercio superior del documento, encontrará primero los datos de contacto del departamento de policía emisor, así como campos para el lugar, la fecha y el número de caso.\n\nJusto debajo se encuentran los datos personales completos, incluyendo nombre, fecha de nacimiento, nacionalidad, dirección y profesión.\n\nA continuación, se detalla la infracción legal específica de la que se le acusa, con líneas separadas que distinguen si se trata de una infracción administrativa (Ordnungswidrigkeit) o de un delito penal (Straftat). La infracción se introduce a mano.\n\nA continuación, la persona afectada autoriza a una autoridad alemana, como el Tribunal de Distrito de Lörrach o el Consejo Regional de Karlsruhe, marcando una casilla, a recibir cartas oficiales y órdenes de sanción en su nombre. Luego, los documentos se envían a la persona que otorga la autorización.\n\nUn breve bloque de texto a continuación informa sobre los derechos en caso de una posible confiscación de artículos y señala que se puede solicitar una decisión judicial en contra sin ningún formulario o plazo específico.\n\nEn el reverso del documento, se informa a la persona de sus obligaciones de cooperación obligatorias, como notificar inmediatamente a la autoridad un cambio de residencia. Cualquier persona sin una dirección fija también debe comunicarse de manera proactiva y regular con la autoridad autorizada, cuyos datos de contacto exactos se enumeran allí nuevamente, para preguntar sobre el correo recibido y recogerlo ellos mismos. Un aviso legal particularmente importante en la parte inferior establece que todos los plazos, por ejemplo, para una apelación contra una sanción, comienzan exactamente el día en que la carta es recibida por la autoridad autorizada en Alemania. El plazo no comienza expresamente solo cuando la persona afectada realmente sostiene o recoge la carta. Las citaciones a una audiencia judicial también pueden notificarse legalmente por esta vía.\n\nCasi al final del documento hay dos preguntas con casillas de Sí/No: aquí la persona puede aceptar pagar una condición monetaria para suspender el procedimiento, y marcar si renuncia a una confirmación postal formal de la suspensión en este caso. La conclusión es el área de firma, donde se marca a qué idioma se tradujo el formulario, si hubo un intérprete presente y que la autorización se otorgó voluntariamente y se entregó una copia. Finalmente, en la parte inferior izquierda, la persona afectada proporciona su firma, mientras que el oficial de policía responsable firma en la parte inferior derecha.",
  it: "Spiegazioni relative al documento Delega di notifica (Zustellungsvollmacht).\n\nNel terzo superiore del documento si trovano prima i dati di contatto del dipartimento di polizia emittente, nonché i campi per il luogo, la data e il numero di pratica.\n\nSubito sotto si trovano le generalità complete, comprensive di nome, data di nascita, nazionalità, indirizzo e professione.\n\nSuccessivamente, viene specificata la violazione di legge contestata, distinguendo in righe separate se si tratta di un illecito amministrativo (Ordnungswidrigkeit) o di un reato penale (Straftat). La violazione viene inserita a mano.\n\nLa persona interessata autorizza quindi un'autorità tedesca, come il tribunale distrettuale di Lörrach o il consiglio regionale di Karlsruhe, barrando una casella, a ricevere lettere ufficiali e decreti penali per suo conto. I documenti vengono poi inoltrati alla persona che rilascia l'autorizzazione.\n\nUn breve blocco di testo sottostante informa sui diritti in caso di eventuale confisca di oggetti e fa presente che è possibile richiedere una decisione giudiziaria in merito senza forme o scadenze specifiche.\n\nSul retro del documento, la persona viene informata dei propri obblighi di collaborazione tassativi, come comunicare tempestivamente all'autorità un eventuale cambio di residenza. Chiunque non abbia una dimora fissa deve inoltre contattare proattivamente e regolarmente l'autorità autorizzata - i cui dati di contatto esatti sono ivi nuovamente elencati - per informarsi sulla posta ricevuta e ritirarla di persona. Un avviso legale particolarmente importante in basso stabilisce che tutte le scadenze, ad esempio per un ricorso contro una sanzione, iniziano esattamente il giorno in cui la lettera viene ricevuta dall'autorità autorizzata in Germania. La scadenza non decorre espressamente solo quando l'interessato tiene effettivamente in mano o ritira la lettera. Anche le citazioni in giudizio possono essere legalmente notificate tramite questo canale.\n\nQuasi alla fine del documento ci sono due domande con caselle Sì/No: qui la persona può accettare di pagare una condizione pecuniaria per archiviare il procedimento, e spuntare se in questo caso rinuncia a una formale conferma postale dell'archiviazione. La conclusione è l'area della firma, dove viene spuntato in quale lingua è stato tradotto il modulo, se era presente un interprete e che l'autorizzazione è stata data volontariamente ed è stata consegnata una copia. Infine, in basso a sinistra, l'interessato appone la propria firma, mentre l'ufficiale di polizia responsabile firma in basso a destra.",
  ru: "Пояснения к документу Доверенность на получение документов (Zustellungsvollmacht).\n\nВ верхней трети документа вы найдете контактные данные выдавшего полицейского участка, а также поля для указания места, даты и номера дела.\n\nСразу под этим следуют полные личные данные, включая имя, дату рождения, гражданство, адрес и профессию.\n\nДалее подробно описывается конкретное правонарушение, в котором вас обвиняют, при этом в отдельных строках указывается, идет ли речь об административном правонарушении (Ordnungswidrigkeit) или уголовном преступлении (Straftat). Правонарушение вписывается от руки.\n\nЗатем заинтересованное лицо уполномочивает немецкий орган, например, Окружной суд Лёрраха или Региональный совет Карлсруэ, поставив галочку в поле, получать официальные письма и постановления о штрафах от его имени. Затем документы пересылаются лицу, предоставляющему полномочия.\n\nКороткий текстовый блок ниже информирует о правах в случае возможной конфискации предметов и указывает на то, что можно запросить судебное решение по этому поводу без какой-либо специальной формы или срока.\n\nНа оборотной стороне документа лицо информируется о своих обязательных обязанностях по сотрудничеству, таких как немедленное уведомление органа о смене места жительства. Любое лицо, не имеющее постоянного адреса, должно также активно и регулярно связываться с уполномоченным органом - точные контактные данные которого снова перечислены там - чтобы узнавать о полученной почте и забирать ее самостоятельно. Особо важное юридическое уведомление внизу гласит, что все сроки, например, для обжалования штрафа, начинаются точно в день получения письма уполномоченным органом в Германии. Срок прямо не начинается только тогда, когда заинтересованное лицо фактически держит в руках или забирает письмо. Повестки в суд также могут быть законно вручены этим путем.\n\nПочти в конце документа есть два вопроса с полями Да/Нет: здесь человек может согласиться выплатить денежное условие для прекращения разбирательства и отметить галочкой, отказывается ли он в этом случае от официального почтового подтверждения о прекращении. Завершает форму область подписи, где отмечается, на какой язык была переведена форма, присутствовал ли переводчик, и что доверенность была выдана добровольно, а копия была вручена. Наконец, внизу слева заинтересованное лицо ставит свою подпись, а ответственный сотрудник полиции расписывается внизу справа.",
  pl: "Wyjaśnienia dotyczące dokumentu Pełnomocnictwo do doręczeń (Zustellungsvollmacht).\n\nW górnej jednej trzeciej dokumentu znajdują się najpierw dane kontaktowe wydającego go wydziału policji, a także pola na miejsce, datę i numer sprawy.\n\nBezpośrednio pod tym znajdują się pełne dane osobowe, w tym imię i nazwisko, data urodzenia, obywatelstwo, adres i zawód.\n\nNastępnie wyszczególnione jest konkretne naruszenie prawa, o które jesteś oskarżony, przy czym w osobnych wierszach odróżnia się, czy jest to wykroczenie administracyjne (Ordnungswidrigkeit), czy przestępstwo kryminalne (Straftat). Naruszenie wpisywane jest odręcznie.\n\nZainteresowana osoba upoważnia następnie organ niemiecki, taki jak Sąd Rejonowy w Lörrach lub Prezydium Rejencji Karlsruhe, zaznaczając odpowiednie pole, do odbierania w jej imieniu oficjalnych listów i nakazów karnych. Dokumenty są następnie przekazywane osobie udzielającej pełnomocnictwa.\n\nKrótki blok tekstowy poniżej informuje o prawach w przypadku ewentualnej konfiskaty przedmiotów i wskazuje, że można wnieść o wydanie orzeczenia sądowego w tej sprawie bez określonej formy lub terminu.\n\nNa odwrocie dokumentu osoba informowana jest o swoich obowiązkowych obowiązkach współpracy, takich jak natychmiastowe powiadomienie organu o zmianie miejsca zamieszkania. Każdy, kto nie ma stałego adresu, musi również proaktywnie i regularnie kontaktować się z upoważnionym organem - którego dokładne dane kontaktowe są tam ponownie wymienione - w celu zapytania o otrzymaną pocztę i osobistego jej odbioru. Szczególnie ważna informacja prawna na dole stanowi, że wszystkie terminy, na przykład na odwołanie się od kary, rozpoczynają się dokładnie w dniu otrzymania listu przez upoważniony organ w Niemczech. Termin wyraźnie nie rozpoczyna się dopiero wtedy, gdy dana osoba faktycznie trzyma w ręku lub odbiera list. Wezwania na rozprawę sądową mogą być również doręczane legalnie tą drogą.\n\nPrawie na końcu dokumentu znajdują się dwa pytania z polami Tak/Nie: tutaj osoba może wyrazić zgodę na zapłacenie warunku pieniężnego w celu umorzenia postępowania i zaznaczyć, czy zrzeka się formalnego pocztowego potwierdzenia umorzenia w tym przypadku. Zakończenie stanowi obszar podpisu, gdzie zaznaczane jest, na jaki język przetłumaczono formularz, czy obecny był tłumacz, oraz że upoważnienie zostało udzielone dobrowolnie, a kopia została wręczona. Ostatecznie w lewym dolnym rogu zainteresowana osoba składa swój podpis, podczas gdy odpowiedzialny funkcjonariusz policji podpisuje się w prawym dolnym rogu.",
  ro: "Explicații referitoare la documentul Împuternicire pentru livrare (Zustellungsvollmacht).\n\nÎn treimea superioară a documentului, veți găsi mai întâi datele de contact ale secției de poliție emitente, precum și câmpuri pentru locație, dată și numărul dosarului.\n\nImediat dedesubt sunt detaliile personale complete, inclusiv numele, data nașterii, naționalitatea, adresa și ocupația.\n\nÎn continuare, este detaliată încălcarea legală specifică de care sunteți acuzat, cu rânduri separate care fac distincția între o infracțiune administrativă (Ordnungswidrigkeit) și o infracțiune penală (Straftat). Încălcarea este introdusă manual.\n\nPersoana vizată autorizează apoi o autoritate germană, cum ar fi Judecătoria Lörrach sau Consiliul Regional Karlsruhe, bifând o căsuță, să primească scrisori oficiale și ordine de penalizare în numele său. Documentele sunt apoi transmise persoanei care acordă autorizația.\n\nUn scurt bloc de text de mai jos consiliază cu privire la drepturile în cazul unei posibile confiscări de bunuri și subliniază că se poate solicita o decizie judecătorească împotriva acesteia fără o formă sau un termen limită specific.\n\nPe spatele documentului, persoana este informată cu privire la obligațiile sale obligatorii de cooperare, cum ar fi notificarea imediată a autorității cu privire la o schimbare de reședință. Orice persoană fără o adresă fixă trebuie, de asemenea, să contacteze în mod proactiv și regulat autoritatea autorizată - ale cărei detalii exacte de contact sunt din nou enumerate acolo - pentru a întreba despre corespondența primită și pentru a o ridica singură. O notificare legală deosebit de importantă din partea de jos precizează că toate termenele limită, de exemplu pentru un apel împotriva unei sancțiuni, încep exact în ziua în care scrisoarea este primită de autoritatea autorizată în Germania. Termenul nu începe în mod expres doar atunci când persoana vizată deține sau ridică scrisoarea în mod efectiv. Citațiile la o audiere în instanță pot fi, de asemenea, notificate în mod legal prin intermediul acestei rute.\n\nAproape la sfârșitul documentului sunt două întrebări cu căsuțe Da/Nu: aici persoana poate fi de acord să plătească o condiție monetară pentru a opri procedurile și poate bifa dacă renunță la o confirmare poștală formală a opririi în acest caz. Concluzia este zona de semnătură, unde se bifează în ce limbă a fost tradus formularul, dacă a fost prezent un interpret și că autorizația a fost dată în mod voluntar și a fost predată o copie. În cele din urmă, în stânga jos, persoana vizată furnizează semnătura sa, în timp ce ofițerul de poliție responsabil semnează în dreapta jos.",
  tr: "Tebligat Vekaletnamesi (Zustellungsvollmacht) belgesine ilişkin açıklamalar.\n\nBelgenin üst üçte birlik kısmında, öncelikle belgeyi veren polis departmanının iletişim bilgilerinin yanı sıra yer, tarih ve dosya numarası için alanlar bulacaksınız.\n\nBunun hemen altında, isim, doğum tarihi, uyruk, adres ve meslek dahil olmak üzere eksiksiz kişisel bilgiler yer almaktadır.\n\nBunu takiben, suçlandığınız belirli yasal ihlal ayrıntılı olarak açıklanır ve idari bir suç (Ordnungswidrigkeit) ile cezai bir suç (Straftat) arasında ayrım yapan ayrı satırlar bulunur. İhlal el ile girilir.\n\nEtkilenen kişi daha sonra bir kutuyu işaretleyerek Lörrach Bölge Mahkemesi veya Karlsruhe Bölge Konseyi gibi bir Alman makamına kendi adına resmi mektuplar ve ceza emirleri alma yetkisi verir. Belgeler daha sonra yetkiyi veren kişiye iletilir.\n\nAşağıdaki kısa bir metin bloğu, eşyaların olası bir müsaderesi durumunda haklar konusunda tavsiyede bulunur ve herhangi bir özel form veya son tarih olmaksızın buna karşı adli bir karar talep edilebileceğine dikkat çeker.\n\nBelgenin arka yüzünde kişi, örneğin bir adres değişikliğini makama derhal bildirmek gibi zorunlu işbirliği yükümlülükleri hakkında bilgilendirilir. Sabit bir adresi olmayan herhangi biri, alınan posta hakkında soru sormak ve postayı kendisi almak için - kesin iletişim bilgileri orada tekrar listelenen - yetkili makamla proaktif ve düzenli olarak iletişime geçmelidir. Alt kısımdaki özellikle önemli bir yasal uyarı, örneğin bir cezaya itiraz gibi tüm son tarihlerin tam olarak mektubun Almanya'daki yetkili makam tarafından alındığı gün başladığını belirtir. Süre, kesinlikle etkilenen kişinin mektubu fiilen elinde tuttuğu veya aldığı anda başlamaz. Mahkeme duruşmasına celpler de bu yolla yasal olarak tebliğ edilebilir.\n\nBelgenin neredeyse sonunda Evet/Hayır kutularının bulunduğu iki soru vardır: Burada kişi işlemleri durdurmak için parasal bir koşul ödemeyi kabul edebilir ve bu durumda durdurmanın resmi posta onayından feragat edip etmediğini işaretleyebilir. Sonuç bölümü, formun hangi dile çevrildiğinin, bir tercümanın bulunup bulunmadığının ve yetkinin gönüllü olarak verildiğinin ve bir kopyasının teslim edildiğinin işaretlendiği imza alanıdır. Son olarak, sol altta etkilenen kişi imzasını atarken, sorumlu polis memuru sağ altta imzalar.",
  sl: "Pojasnila k dokumentu Pooblastilo za vročanje (Zustellungsvollmacht).\n\nV zgornji tretjini dokumenta boste najprej našli kontaktne podatke policijske uprave, ki je izdala dokument, ter polja za kraj, datum in številko zadeve.\n\nNeposredno pod tem so popolni osebni podatki, vključno z imenom, datumom rojstva, državljanstvom, naslovom in poklicem.\n\nSledi podroben opis konkretne pravne kršitve, ki se vam očita, z ločenimi vrsticami, ki razlikujejo med upravnim prekrškom (Ordnungswidrigkeit) in kaznivim dejanjem (Straftat). Kršitev se vpiše ročno.\n\nPrizadeta oseba nato z označitvijo okenca pooblasti nemški organ, kot je okrajno sodišče Lörrach ali regionalni svet Karlsruhe, da v njenem imenu sprejema uradna pisma in kazenske naloge. Dokumenti se nato posredujejo osebi, ki je izdala pooblastilo.\n\nKratek blok besedila spodaj svetuje o pravicah v primeru morebitnega odvzema predmetov in opozarja, da je mogoče zoper to zahtevati sodno odločbo brez posebne oblike ali roka.\n\nNa hrbtni strani dokumenta je oseba obveščena o svojih obveznostih sodelovanja, kot je takojšnje obvestilo organu o spremembi prebivališča. Vsakdo, ki nima stalnega naslova, se mora tudi proaktivno in redno obračati na pooblaščeni organ - katerega natančni kontaktni podatki so tam ponovno navedeni - in se pozanimati o prejeti pošti ter jo sam prevzeti. Posebej pomembno pravno obvestilo na dnu določa, da vsi roki, na primer za pritožbo zoper kazen, začnejo teči natanko na dan, ko pismo prejme pooblaščeni organ v Nemčiji. Rok izrecno ne začne teči šele takrat, ko prizadeta oseba pismo dejansko drži v rokah ali prevzame. Po tej poti se lahko zakonito vročajo tudi vabila na glavno obravnavo.\n\nSkoraj na koncu dokumenta sta dve vprašanji z okenci Da/Ne: tukaj se lahko oseba strinja s plačilom denarnega pogoja za ustavitev postopka in označi, ali se v tem primeru odpoveduje uradni poštni potrditvi ustavitve. Zaključek je področje za podpis, kjer se označi, v kateri jezik je bil obrazec preveden, ali je bil prisoten tolmač in da je bilo pooblastilo dano prostovoljno in izročena kopija. Na koncu, spodaj levo, prizadeta oseba odloži svoj podpis, odgovorni policist pa se podpiše spodaj desno.",
  hu: "Magyarázatok a Kézbesítési meghatalmazás (Zustellungsvollmacht) dokumentumhoz.\n\nA dokumentum felső harmadában először a kiállító rendőrkapitányság elérhetőségeit találja, valamint a hely, a dátum és az ügyszám mezőit.\n\nKözvetlenül ez alatt találhatók a teljes személyes adatok, beleértve a nevet, születési időt, állampolgárságot, címet és foglalkozást.\n\nEzt követően részletesen ismertetik azt a konkrét jogsértést, amellyel vádolják, külön sorokban megkülönböztetve, hogy közigazgatási szabálysértésről (Ordnungswidrigkeit) vagy bűncselekményről (Straftat) van-e szó. A jogsértést kézzel írják be.\n\nAz érintett személy ezután egy jelölőnégyzet bepipálásával felhatalmaz egy német hatóságot, például a Lörrachi Kerületi Bíróságot vagy a Karlsruhe Regionális Tanácsot, hogy hivatalos leveleket és büntetőparancsokat vegyen át a nevében. A dokumentumokat ezután továbbítják a meghatalmazást adó személynek.\n\nAz alábbi rövid szövegblokk a tárgyak esetleges elkobzása esetén fennálló jogokról ad tájékoztatást, és rámutat arra, hogy ezen bírósági határozat ellen bármilyen formanyomtatvány vagy határidő nélkül lehet kérelmet benyújtani.\n\nA dokumentum hátoldalán az illetőt tájékoztatják kötelező együttműködési kötelezettségeiről, például arról, hogy azonnal értesítenie kell a hatóságot a lakcímváltozásról. Akinek nincs állandó lakcíme, annak is proaktívan és rendszeresen kapcsolatba kell lépnie a meghatalmazott hatósággal - amelynek pontos elérhetőségei ott ismét szerepelnek -, hogy érdeklődjön a kapott postáról, és maga vegye át azt. Egy különösen fontos jogi nyilatkozat az alján kimondja, hogy minden határidő, például a büntetés elleni fellebbezés esetén, pontosan azon a napon kezdődik, amikor a levelet a meghatalmazott hatóság Németországban kézhez kapja. A határidő kifejezetten nem csak akkor kezdődik, amikor az érintett személy ténylegesen a kezében tartja vagy átveszi a levelet. Bírósági tárgyalásra szóló idézések ezen az úton is jogszerűen kézbesíthetők.\n\nMajdnem a dokumentum végén két kérdés található Igen/Nem jelölőnégyzetekkel: Itt a személy beleegyezhet egy pénzbeli feltétel kifizetésébe az eljárás megszüntetése érdekében, és bejelölheti, hogy ebben az esetben lemond-e a megszüntetés hivatalos postai visszaigazolásáról. A befejezés az aláírási terület, ahol bejelölik, hogy az űrlapot milyen nyelvre fordították le, jelen volt-e tolmács, valamint hogy a meghatalmazást önként adták meg, és átadtak egy másolatot. Végül bal alsó sarokban az érintett személy látja el kézjegyével, míg a felelős rendőrtiszt a jobb alsó sarokban írja alá.",
  uk: "Пояснення до документа Довіреність на отримання документів (Zustellungsvollmacht).\n\nУ верхній третині документа ви спочатку знайдете контактні дані поліцейського відділку, що його видав, а також поля для зазначення місця, дати та номера справи.\n\nБезпосередньо під цим йдуть повні особисті дані, включаючи ім'я, дату народження, громадянство, адресу та професію.\n\nПісля цього детально описується конкретне правопорушення, у якому вас звинувачують, при цьому в окремих рядках розрізняється, чи йдеться про адміністративне правопорушення (Ordnungswidrigkeit) або кримінальний злочин (Straftat). Правопорушення вписується від руки.\n\nПотім зацікавлена особа уповноважує німецький орган, такий як Окружний суд Лерраха або Регіональна рада Карлсруе, поставивши галочку в полі, отримувати офіційні листи та постанови про штрафи від її імені. Потім документи пересилаються особі, яка надає повноваження.\n\nКороткий текстовий блок нижче інформує про права у разі можливої конфіскації предметів і вказує на те, що можна подати запит на судове рішення щодо цього без будь-якої спеціальної формы або строку.\n\nНа зворотному боці документа особу інформують про її обов'язкові зобов'язання щодо співпраці, такі як негайне повідомлення органу про зміну місця проживання. Будь-яка особа без постійної адреси також повинна проактивно і регулярно звертатися до уповноваженого органу - точні контактні дані якого там знову перераховані - щоб запитувати про отриману пошту і забирати її самостійно. Особливо важливе юридичне повідомлення внизу стверджує, що всі строки, наприклад, для оскарження штрафу, починаються рівно в день отримання листа уповноваженим органом у Німеччині. Строк прямо не починається лише тоді, коли зацікавлена особа фактично тримає в руках або забирає лист. Повістки до суду також можуть бути законно вручені цим шляхом.\n\nМайже в кінці документа є два питання з полями Так/Ні: тут особа може погодитися виплатити грошову умову для припинення провадження і зазначити, чи відмовляється вона від офіційного поштового підтвердження про припинення у цьому випадку. Завершує форму область підпису, де зазначається, на яку мову було перекладено форму, чи був присутній перекладач, і що довіреність була надана добровільно, а копія була вручена. Нарешті, внизу зліва зацікавлена особа ставить свій підпис, а відповідальний співробітник поліції розписується внизу справа.",
  hi: "डिलीवरी प्राधिकरण (Zustellungsvollmacht) दस्तावेज़ के लिए स्पष्टीकरण।\n\nदस्तावेज़ के ऊपरी तीसरे भाग में, आपको सबसे पहले जारीकर्ता पुलिस विभाग के संपर्क विवरण के साथ-साथ स्थान, दिनांक और केस नंबर के लिए फ़ील्ड मिलेंगे।\n\nइसके ठीक नीचे नाम, जन्म तिथि, राष्ट्रीयता, पता और व्यवसाय सहित संपूर्ण व्यक्तिगत विवरण हैं।\n\nइसके बाद, जिस विशिष्ट कानूनी उल्लंघन का आप पर आरोप है, उसका विवरण दिया गया है, जिसमें अलग-अलग लाइनें प्रशासनिक अपराध (Ordnungswidrigkeit) और एक आपराधिक अपराध (Straftat) के बीच अंतर करती हैं। उल्लंघन हाथ से दर्ज किया गया है।\n\nप्रभावित व्यक्ति फिर एक बॉक्स की जाँच करके एक जर्मन प्राधिकरण, जैसे कि लोर्राच के जिला न्यायालय या कार्ल्सरूए की क्षेत्रीय परिषद को अपनी ओर से आधिकारिक पत्र और जुर्माना आदेश प्राप्त करने के लिए अधिकृत करता है। इसके बाद दस्तावेज़ प्राधिकरण देने वाले व्यक्ति को भेज दिए जाते हैं।\n\nनीचे एक छोटा टेक्स्ट ब्लॉक वस्तुओं के संभावित जब्ती की स्थिति में अधिकारों पर सलाह देता है और यह बताता है कि बिना किसी विशिष्ट रूप या समय सीमा के इसके खिलाफ न्यायिक निर्णय का अनुरोध किया जा सकता है।\n\nदस्तावेज़ के पीछे, व्यक्ति को सहयोग करने के उनके अनिवार्य दायित्वों के बारे में सूचित किया जाता है, जैसे निवास के परिवर्तन के प्राधिकरण को तुरंत सूचित करना। बिना किसी निश्चित पते वाले व्यक्ति को प्राप्त मेल के बारे में पूछने और उसे स्वयं एकत्र करने के लिए अधिकृत प्राधिकरण - जिसका सटीक संपर्क विवरण वहां फिर से सूचीबद्ध है - से सक्रिय रूप से और नियमित रूप से संपर्क करना चाहिए। नीचे एक विशेष रूप से महत्वपूर्ण कानूनी नोटिस में कहा गया है कि सभी समय सीमाएँ, उदाहरण के लिए किसी जुर्माने के खिलाफ अपील के लिए, ठीक उसी दिन शुरू होती हैं जिस दिन जर्मनी में अधिकृत प्राधिकरण द्वारा पत्र प्राप्त होता है। समय सीमा स्पष्ट रूप से केवल तभी शुरू नहीं होती है जब प्रभावित व्यक्ति वास्तव में पत्र को पकड़ता है या एकत्र करता है। अदालत की सुनवाई के लिए सम्मन कानूनी रूप से इस मार्ग के माध्यम से भी दिए जा सकते हैं।\n\nदस्तावेज़ के लगभग अंत में यस/नो बॉक्स के साथ दो प्रश्न हैं: यहां व्यक्ति कार्यवाही को बंद करने के लिए मौद्रिक शर्त का भुगतान करने के लिए सहमत हो सकता है, और यह जांच कर सकता है कि क्या वे इस मामले में बंद होने की औपचारिक डाक पुष्टि को माफ करते हैं। निष्कर्ष हस्ताक्षर क्षेत्र है, जहां यह जांचा जाता है कि फॉर्म का किस भाषा में अनुवाद किया गया था, क्या एक दुभाषिया मौजूद था, और यह कि प्राधिकरण स्वेच्छा से दिया गया था और एक प्रति सौंपी गई थी। अंत में, नीचे बाईं ओर, प्रभावित व्यक्ति अपना हस्ताक्षर प्रदान करता है, जबकि जिम्मेदार पुलिस अधिकारी नीचे दाईं ओर हस्ताक्षर करता है।",
  bg: "Обяснения към документа Пълномощно за връчване (Zustellungsvollmacht).\n\nВ горната третина на документа ще намерите първо данните за контакт на издаващото полицейско управление, както и полета за мястото, датата и номера на преписката.\n\nНепосредствено под това са пълните лични данни, включително име, дата на раждане, националност, адрес и професия.\n\nСлед това се описва подробно конкретното законово нарушение, в което сте обвинени, като отделни редове правят разлика между административно нарушение (Ordnungswidrigkeit) и престъпление (Straftat). Нарушението се въвежда на ръка.\n\nСлед това засегнатото лице упълномощава немски орган, като например Районен съд Льорах или Регионалния съвет на Карлсруе, като постави отметка в квадратче, да получава официални писма и наказателни постановления от негово име. След това документите се препращат на лицето, даващо пълномощното.\n\nКратък текстов блок по-долу съветва относно правата в случай на евентуална конфискация на вещи и посочва, че може да се поиска съдебно решение срещу това без някаква конкретна форма или краен срок.\n\nНа гърба на документа лицето се информира за неговите задължителни задължения за сътрудничество, като незабавно уведомяване на органа за промяна на местожителството. Всяко лице без постоянен адрес трябва също така проактивно и редовно да се свързва с упълномощения орган - чиито точни данни за контакт са изброени там отново - за да попита за получена поща и да я вземе само. Особено важно правно съобщение в долната част гласи, че всички срокове, например за обжалване срещу наказание, започват точно в деня, в който писмото е получено от упълномощения орган в Германия. Срокът изрично не започва едва когато засегнатото лице действително държи или вземе писмото. Призовките за съдебно заседание също могат да бъдат връчени законно по този начин.\n\nПочти в края на документа има два въпроса с квадратчета Да/Не: Тук лицето може да се съгласи да плати парично условие за прекратяване на производството и да отметне дали се отказва от официално пощенско потвърждение за прекратяването в този случай. Заключението е областта за подпис, където се отбелязва на какъв език е преведен формулярът, дали е присъствал преводач и че пълномощното е дадено доброволно и е връчено копие. Накрая, долу вляво, засегнатото лице полага подписа си, докато отговорният полицейски служител се подписва долу вдясно.",
  cs: "Vysvětlivky k dokumentu Plná moc pro doručování (Zustellungsvollmacht).\n\nV horní třetině dokumentu najdete nejprve kontaktní údaje vydávajícího policejního oddělení a také pole pro místo, datum a číslo případu.\n\nPřímo pod tím jsou kompletní osobní údaje, včetně jména, data narození, národnosti, adresy a povolání.\n\nPoté je podrobně popsáno konkrétní porušení zákona, ze kterého jste obviněni, se samostatnými řádky rozlišujícími mezi správním deliktem (Ordnungswidrigkeit) a trestným činem (Straftat). Porušení je zapsáno ručně.\n\nDotčená osoba poté zaškrtnutím políčka zmocní německý orgán, jako je okresní soud Lörrach nebo regionální rada Karlsruhe, k přijímání úředních dopisů a trestních příkazů jejím jménem. Dokumenty jsou poté předány osobě, která plnou moc udělila.\n\nKrátký textový blok níže radí ohledně práv v případě případného zabavení věcí a upozorňuje, že proti tomu lze požadovat soudní rozhodnutí bez jakékoli konkrétní formy nebo lhůty.\n\nNa zadní straně dokumentu je osoba informována o svých povinných povinnostech ke spolupráci, jako je okamžité oznámení změny bydliště orgánu. Každý, kdo nemá stálou adresu, musí také proaktivně a pravidelně kontaktovat pověřený orgán - jehož přesné kontaktní údaje jsou zde opět uvedeny - a zeptat se na přijatou poštu a sám si ji vyzvednout. Zvláště důležité právní upozornění ve spodní části uvádí, že všechny lhůty, například pro odvolání proti trestu, začínají přesně v den, kdy dopis obdrží pověřený orgán v Německu. Lhůta výslovně nezačíná plynout teprve tehdy, když dotčená osoba dopis skutečně drží nebo si jej vyzvedne. Předvolání k soudnímu jednání lze rovněž legálně doručit touto cestou.\n\nTéměř na konci dokumentu jsou dvě otázky s políčky Ano/Ne: Zde může osoba souhlasit se zaplacením peněžité podmínky pro zastavení řízení a zaškrtnout, zda se v tomto případě vzdává formálního poštovního potvrzení o zastavení. Závěrem je oblast podpisu, kde se zaškrtává, do jakého jazyka byl formulář přeložen, zda byl přítomen tlumočník a že plná moc byla udělena dobrovolně a kopie byla předána. Nakonec, vlevo dole, připojí svůj podpis dotčená osoba, zatímco odpovědný policista se podepíše vpravo dole.",
  lt: "Dokumento „Įgaliojimas įteikti dokumentus“ (Zustellungsvollmacht) paaiškinimai.\n\nViršutiniame dokumento trečdalyje pirmiausia rasite jį išdavusio policijos skyriaus kontaktinius duomenis, taip pat laukelius vietai, datai ir bylos numeriui.\n\nTiesiai po to yra išsamūs asmens duomenys, įskaitant vardą, pavardę, gimimo datą, pilietybę, adresą ir profesiją.\n\nPo to išsamiai aprašomas konkretus teisės pažeidimas, kuriuo esate kaltinamas, atskiromis eilutėmis atskiriant administracinį nusižengimą (Ordnungswidrigkeit) nuo nusikalstamos veikos (Straftat). Pažeidimas įrašomas ranka.\n\nTuomet suinteresuotas asmuo pažymėdamas langelį įgalioja Vokietijos instituciją, pvz., Lörrach apylinkės teismą arba Karlsrūhės regioninę tarybą, jo vardu gauti oficialius laiškus ir baudžiamuosius įsakymus. Tada dokumentai persiunčiami įgaliojimą suteikusiam asmeniui.\n\nŽemiau esančiame trumpame teksto bloke patariama apie teises galimo daiktų konfiskavimo atveju ir atkreipiamas dėmesis, kad dėl to galima prašyti teismo sprendimo be jokios specialios formos ar termino.\n\nDokumento kitoje pusėje asmuo informuojamas apie privalomas bendradarbiavimo pareigas, pavyzdžiui, nedelsiant pranešti institucijai apie gyvenamosios vietos pasikeitimą. Bet kuris asmuo, neturintis nuolatinio adreso, taip pat turi iniciatyviai ir reguliariai susisiekti su įgaliota institucija - kurios tikslūs kontaktiniai duomenys ten vėl išvardyti -, kad pasiteirautų apie gautą paštą ir pats jį atsiimtų. Ypač svarbiame teisiniame pranešime apačioje nurodoma, kad visi terminai, pavyzdžiui, apeliacijai dėl baudos, prasideda tiksliai tą dieną, kai laišką gauna įgaliota institucija Vokietijoje. Terminas aiškiai neprasideda tik tada, kai suinteresuotas asmuo faktiškai laiko rankose arba atsiima laišką. Šaukimai į teismo posėdį taip pat gali būti teisėtai įteikti šiuo būdu.\n\nBeveik dokumento pabaigoje yra du klausimai su langeliais Taip/Ne: Čia asmuo gali sutikti sumokėti piniginę sąlygą, kad būtų nutrauktas bylos nagrinėjimas, ir pažymėti, ar tokiu atveju atsisako formalaus pašto patvirtinimo apie nutraukimą. Pabaiga yra parašo sritis, kurioje pažymima, į kokią kalbą forma buvo išversta, ar dalyvavo vertėjas, ir kad įgaliojimas buvo duotas savanoriškai, o kopija buvo įteikta. Galiausiai, apačioje kairėje, suinteresuotas asmuo pasirašo, o atsakingas policijos pareigūnas pasirašo apačioje dešinėje.",
  nl: "Toelichting bij het document Bezorgingsmachtiging (Zustellungsvollmacht).\n\nIn het bovenste derde deel van het document vindt u eerst de contactgegevens van het uitgevende politiebureau, evenals velden voor de locatie, datum en het dossiernummer.\n\nDirect daaronder staan de volledige persoonsgegevens, waaronder naam, geboortedatum, nationaliteit, adres en beroep.\n\nHierna wordt de specifieke wettelijke overtreding waarvan u wordt beschuldigd gedetailleerd, met aparte regels die onderscheid maken tussen een administratieve overtreding (Ordnungswidrigkeit) en een strafbaar feit (Straftat). De overtreding wordt met de hand ingevoerd.\n\nDe betrokkene machtigt vervolgens een Duitse autoriteit, zoals de rechtbank van Lörrach of de regionale raad van Karlsruhe, door een vakje aan te vinken, om namens hem/haar officiële brieven en strafbeschikkingen in ontvangst te nemen. De documenten worden vervolgens doorgestuurd naar de persoon die de machtiging verleent.\n\nEen kort tekstblok hieronder adviseert over de rechten in geval van een mogelijke inbeslagname van voorwerpen en wijst erop dat men hiertegen zonder specifieke vorm of termijn een rechterlijke beslissing kan aanvragen.\n\nOp de achterkant van het document wordt de persoon geïnformeerd over zijn/haar verplichte medewerkingsplichten, zoals het onmiddellijk op de hoogte stellen van de autoriteit van een adreswijziging. Iedereen zonder vast adres moet ook proactief en regelmatig contact opnemen met de gemachtigde autoriteit - waarvan de exacte contactgegevens daar opnieuw worden vermeld - om te informeren naar ontvangen post en deze zelf op te halen. Een bijzonder belangrijke juridische kennisgeving onderaan stelt dat alle termijnen, bijvoorbeeld voor een beroep tegen een straf, precies beginnen op de dag dat de brief wordt ontvangen door de gemachtigde autoriteit in Duitsland. De termijn begint uitdrukkelijk niet pas wanneer de betrokkene de brief daadwerkelijk in handen heeft of ophaalt. Dagvaardingen voor een rechtszitting kunnen via deze route ook legaal worden betekend.\n\nBijna aan het end van het document staan twee vragen met Ja/Nee-vakjes: Hier kan de persoon ermee instemmen om een geldelijke voorwaarde te betalen om de procedure stop te zetten, en aanvinken of hij/zij in dit geval afziet van een formele schriftelijke bevestiging van de stopzetting. De afsluiting is het handtekeningengedeelte, waar wordt aangevinkt in welke taal het formulier is vertaald, of er een tolk aanwezig was, en dat de machtiging vrijwillig is gegeven en er een kopie is overhandigd. Ten slotte plaatst de betrokkene linksonder zijn/haar handtekening, terwijl de verantwoordelijke politieagent rechtsonder tekent.",
  hr: "Objašnjenja uz dokument Punomoć za dostavu (Zustellungsvollmacht).\n\nU gornjoj trećini dokumenta prvo ćete pronaći kontakt podatke policijske uprave koja je izdala dokument, kao i polja za mjesto, datum i broj spisa.\n\nNeposredno ispod toga nalaze se potpuni osobni podaci, uključujući ime, datum rođenja, nacionalnost, adresu i zanimanje.\n\nNakon toga detaljno je opisan konkretni pravni prekršaj za koji vas se tereti, s odvojenim recima koji razlikuju upravni prekršaj (Ordnungswidrigkeit) i kazneno djelo (Straftat). Prekršaj se unosi ručno.\n\nPogođena osoba zatim označavanjem kućice ovlašćuje njemačko tijelo, poput Okružnog suda u Lörrachu ili Regionalnog vijeća Karlsruhe, da u njezino ime prima službena pisma i kaznene naloge. Dokumenti se zatim prosljeđuju osobi koja daje punomoć.\n\nKratki tekstualni blok u nastavku savjetuje o pravima u slučaju moguće zapljene predmeta i ističe da se protiv toga može zatražiti sudska odluka bez određenog obrasca ili roka.\n\nNa poleđini dokumenta osoba se informira o svojim obvezama suradnje, kao što je hitna obavijest nadležnom tijelu o promjeni prebivališta. Svi koji nemaju stalnu adresu također se moraju proaktivno i redovito javljati ovlaštenom tijelu - čiji su točni kontakt podaci tamo ponovno navedeni - kako bi se raspitali o primljenoj pošti i sami je preuzeli. Posebno važna pravna obavijest na dnu navodi da svi rokovi, primjerice za žalbu na kaznu, počinju teći točno onog dana kada pismo zaprimi ovlašteno tijelo u Njemačkoj. Rok izričito ne počinje teći tek kada pogođena osoba stvarno drži ili preuzme pismo. Sudski pozivi za sudsku raspravu također se mogu legalno dostaviti ovim putem.\n\nGotovo na kraju dokumenta nalaze se dva pitanja s kućicama Da/Ne: Ovdje osoba može pristati platiti novčani uvjet za obustavu postupka i označiti odriče li se u ovom slučaju formalne poštanske potvrde o obustavi. Zaključak je prostor za potpis, gdje se označava na koji je jezik obrazac preveden, je li bio prisutan tumač te da je punomoć dana dobrovoljno i da je uručena kopija. Na kraju, dolje lijevo, pogođena osoba daje svoj potpis, dok odgovorni policajac potpisuje dolje desno."
};

export default function App() {
  const [currentLang, setCurrentLang] = useState<string | null>(null);
  const [currentLegal, setCurrentLegal] = useState<string | null>(null);

  const resetToHome = () => {
    setCurrentLang(null);
    setCurrentLegal(null);
  };

  const goBack = () => {
    if (currentLegal) {
      setCurrentLegal(null);
    } else if (currentLang) {
      setCurrentLang(null);
    }
  };

  const renderLanguageSelection = () => {
    return (
      <div className="space-y-8 animate-fade-in-up">
        
        <div className="text-center">
          <div className="inline-flex items-center justify-center p-4 bg-teal-50 rounded-full mb-4 text-teal-500 shadow-sm border border-teal-100">
            <FileCheck size={36} strokeWidth={1.5} />
          </div>
          <h2 className="text-3xl sm:text-4xl font-extrabold text-slate-800 tracking-tight">Zustellungsvollmacht</h2>
          <p className="text-slate-500 mt-3 text-lg font-medium">Sprache des Fahrers wählen / Select the driver's language</p>
        </div>

        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-4 sm:gap-6 p-2 max-w-5xl mx-auto w-full">
          {LANGUAGES.map((lang) => (
            <button
              key={lang.id}
              onClick={() => setCurrentLang(lang.id)}
              className="group flex flex-col items-center justify-center p-6 bg-white rounded-3xl shadow-[0_4px_20px_rgb(0,0,0,0.03)] border border-slate-100 transition-all duration-300 hover:shadow-[0_8px_30px_rgb(0,0,0,0.08)] hover:border-teal-200 hover:-translate-y-1"
            >
              <div className="relative w-16 h-12 mb-4">
                <div className="absolute inset-0 bg-black/5 rounded-md transform group-hover:scale-110 transition-transform duration-300 blur-sm" />
                <img 
                  src={`https://flagcdn.com/w160/${lang.countryCode}.png`} 
                  alt={`${lang.name} Flagge`} 
                  className="relative w-full h-full object-cover rounded-md shadow-sm border border-slate-200 transform group-hover:scale-110 transition-transform duration-300"
                />
              </div>
              <span className="font-bold text-slate-800 text-lg tracking-tight group-hover:text-teal-600 transition-colors">{lang.name}</span>
              <span className="text-xs font-medium text-slate-400 mt-1.5 uppercase tracking-wider">{lang.germanCountry}</span>
            </button>
          ))}
        </div>
      </div>
    );
  };

  const renderTextView = () => {
    const selectedLangObj = LANGUAGES.find(l => l.id === currentLang);
    
    // @ts-ignore
    const textToDisplay = TEXT_DATABASE[currentLang] || "Text noch nicht verfügbar.";

    return (
      <div className="p-2 sm:p-4 max-w-4xl mx-auto w-full animate-fade-in-up">
        <div className="bg-white rounded-[2rem] shadow-[0_20px_50px_rgb(0,0,0,0.08)] overflow-hidden border border-slate-100">
          
          <div className="p-6 sm:p-8 bg-gradient-to-r from-teal-400 to-emerald-500 flex flex-col sm:flex-row items-center justify-between gap-4 relative overflow-hidden">
            <div className="absolute -right-10 -top-10 w-40 h-40 bg-white/10 rounded-full blur-2xl" />
            
            <div className="flex items-center space-x-5 relative z-10">
              <img 
                src={`https://flagcdn.com/w80/${selectedLangObj?.countryCode}.png`} 
                alt="Flagge" 
                className="w-14 h-auto rounded-md shadow-md border-2 border-white/20"
              />
              <div>
                <h2 className="text-2xl sm:text-3xl font-extrabold text-white tracking-tight">Zustellungsvollmacht</h2>
                <p className="text-white/80 font-medium mt-1">{selectedLangObj?.name}</p>
              </div>
            </div>
            <FileCheck size={48} className="text-white/90 drop-shadow-md relative z-10 hidden sm:block" strokeWidth={1.5} />
          </div>

          <div className="relative p-8 sm:p-14 min-h-[350px] flex items-center justify-start bg-slate-50/50">
            <div className="absolute top-10 right-10 text-slate-200/50">
              <MessageSquareQuote size={120} strokeWidth={1} />
            </div>
            
            <div className="relative z-10 text-xl sm:text-2xl text-slate-700 leading-relaxed font-semibold text-left tracking-tight whitespace-pre-wrap w-full">
              {textToDisplay}
            </div>
          </div>
        </div>
      </div>
    );
  };

  const renderImpressum = () => (
    <div className="p-6 sm:p-10 max-w-3xl mx-auto w-full bg-white rounded-3xl shadow-[0_8px_30px_rgb(0,0,0,0.04)] border border-slate-100 animate-fade-in-up">
      <h2 className="text-3xl font-extrabold text-slate-800 tracking-tight mb-8 text-center uppercase">Impressum</h2>
      
      <div className="space-y-8">
        <div>
          <h3 className="text-xl font-bold text-slate-800 mb-3">Angaben gemäß § 5 TMG</h3>
          <p className="text-slate-600 leading-relaxed">
            Simon Demel<br />
            Ellen-Gottlieb Straße 15<br />
            79106 Freiburg im Breisgau
          </p>
        </div>

        <div>
          <h3 className="text-xl font-bold text-slate-800 mb-3">Kontakt</h3>
          <p className="text-slate-600 leading-relaxed">
            E-Mail: <a href="mailto:simondemel@gmx.de" className="text-blue-600 hover:text-blue-800 transition-colors">simondemel@gmx.de</a>
          </p>
        </div>
      </div>
    </div>
  );

  const renderPrivacy = () => (
    <div className="p-6 sm:p-10 max-w-3xl mx-auto w-full bg-white rounded-3xl shadow-[0_8px_30px_rgb(0,0,0,0.04)] border border-slate-100 animate-fade-in-up">
      <h2 className="text-3xl font-extrabold text-slate-800 tracking-tight mb-8 text-center">Datenschutzerklärung</h2>
      
      <div className="space-y-8">
        <div>
          <h3 className="text-xl font-bold text-slate-800 mb-3">1. Datenerfassung & Lokale Verarbeitung</h3>
          <p className="text-slate-600 leading-relaxed">
            Diese Applikation arbeitet primär vollständig lokal auf Ihrem Endgerät ("Client-Side"). Es werden von der Applikationslogik selbst keinerlei personenbezogene Daten (wie Berechnungen, Gewichte, Winkel etc.) an externe Server übertragen oder dort gespeichert.
          </p>
        </div>

        <div>
          <h3 className="text-xl font-bold text-slate-800 mb-3">2. Hosting (Vercel)</h3>
          <p className="text-slate-600 leading-relaxed">
            Wir hosten unsere Website bei Vercel. Anbieter ist die Vercel Inc., 340 S Lemon Ave #4133, Walnut, CA 91789, USA. Wenn Sie unsere Website besuchen, erfasst Vercel serverseitig standardmäßig Verbindungsdaten (z. B. Ihre IP-Adresse, Browsertyp, Datum und Uhrzeit des Abrufs) in sogenannten Server-Logfiles, um die fehlerfreie Auslieferung der Website und die IT-Sicherheit zu gewährleisten. Die Erfassung dieser Daten erfolgt auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO. Weitere Details finden Sie in der Datenschutzerklärung von Vercel.
          </p>
        </div>

        <div>
          <h3 className="text-xl font-bold text-slate-800 mb-3">3. Cookies & Tracking</h3>
          <p className="text-slate-600 leading-relaxed">
            Diese Anwendung verwendet keine eigenen Tracking-Cookies oder Analyse-Werkzeuge (z. B. Google Analytics), um das Nutzerverhalten auszuwerten oder Profile zu erstellen.
          </p>
        </div>
      </div>
    </div>
  );

  return (
    <>
      <style>
        {`
          @keyframes fadeInUp {
            from { opacity: 0; transform: translateY(15px); }
            to { opacity: 1; transform: translateY(0); }
          }
          .animate-fade-in-up {
            animation: fadeInUp 0.5s cubic-bezier(0.16, 1, 0.3, 1) forwards;
          }
        `}
      </style>
      
      <div className="min-h-screen bg-[#f8fafc] bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-slate-100 via-slate-50 to-slate-100 font-sans flex flex-col">
        
        <main className="flex-1 max-w-6xl w-full mx-auto p-4 sm:p-6 lg:p-8 flex flex-col pt-6 sm:pt-10">
          
          {(currentLang || currentLegal) && (
            <div className="flex items-center justify-between mb-8 w-full animate-fade-in-up">
              <button 
                onClick={goBack}
                className="group flex items-center space-x-2 bg-white shadow-sm border border-slate-200 hover:bg-slate-50 hover:border-slate-300 text-slate-700 px-4 py-2.5 rounded-xl transition-all duration-200 font-medium"
              >
                <ArrowLeft size={18} className="group-hover:-translate-x-1 transition-transform" />
                <span>Zurück</span>
              </button>

              <button 
                onClick={resetToHome}
                className="p-2.5 bg-white shadow-sm border border-slate-200 hover:bg-slate-50 hover:border-slate-300 text-slate-700 rounded-xl transition-all duration-200"
                title="Zurück zum Start"
              >
                <Home size={20} />
              </button>
            </div>
          )}

          {!currentLegal && !currentLang && renderLanguageSelection()}
          {!currentLegal && currentLang && renderTextView()}
          {currentLegal === 'impressum' && renderImpressum()}
          {currentLegal === 'privacy' && renderPrivacy()}
        </main>

        <footer className="mt-auto py-6 border-t border-slate-200/60 bg-slate-50/30">
          <div className="max-w-6xl mx-auto px-4 flex justify-center space-x-6 text-sm font-medium text-slate-500">
            <button onClick={() => setCurrentLegal('impressum')} className="hover:text-slate-800 transition-colors">Impressum</button>
            <span>|</span>
            <button onClick={() => setCurrentLegal('privacy')} className="hover:text-slate-800 transition-colors">Datenschutz</button>
          </div>
        </footer>
      </div>
    </>
  );
}
